/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
#include "avl.h"
/* Header for class DataHelper */

#ifndef _Included_DataHelper
#define _Included_DataHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DataHelper
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DataHelper_init
        (JNIEnv *, jclass);

/*
 * Class:     DataHelper
 * Method:    insert
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_DataHelper_insert
        (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     DataHelper
 * Method:    remove
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_DataHelper_remove
        (JNIEnv *, jobject, jlong);

/*
 * Class:     DataHelper
 * Method:    resetPosition
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_DataHelper_resetPosition
        (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     DataHelper
 * Method:    findAVLNode
 * Signature: (I)LAVLNode;
 */
JNIEXPORT jobject JNICALL Java_DataHelper_findAVLNode
        (JNIEnv *, jobject, jlong);

/*
 * Class:     DataHelper
 * Method:    getRoot
 * Signature: ()V
 */
JNIEXPORT jobject JNICALL Java_DataHelper_getRoot
        (JNIEnv *, jobject);


JNIEXPORT void JNICALL Java_DataHelper_insert
        (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     DataHelper
 * Method:    fireAll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_DataHelper_fireAll
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
