/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DataHelper */

#ifndef _Included_DataHelper
#define _Included_DataHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DataHelper
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DataHelper_init
  (JNIEnv *, jclass);

/*
 * Class:     DataHelper
 * Method:    insert
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_DataHelper_insert
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     DataHelper
 * Method:    remove
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_DataHelper_remove
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     DataHelper
 * Method:    fireAll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_DataHelper_fireAll
  (JNIEnv *, jobject, jint);

/*
 * Class:     DataHelper
 * Method:    resetPosition
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_DataHelper_resetPosition
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     DataHelper
 * Method:    findAVLNode
 * Signature: (JI)LAVLNode;
 */
JNIEXPORT jobject JNICALL Java_DataHelper_findAVLNode
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     DataHelper
 * Method:    getRoot
 * Signature: (I)LAVLNode;
 */
JNIEXPORT jobject JNICALL Java_DataHelper_getRoot
  (JNIEnv *, jobject, jint);

/*
 * Class:     DataHelper
 * Method:    merge
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DataHelper_merge
  (JNIEnv *, jobject);

/*
 * Class:     DataHelper
 * Method:    split
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_DataHelper_split
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
